% This code requires a solution to already be loaded. A solution can be
% generated by running the script `get_solution`.

fig=figure();
hold on
leg=[];
for t=[0 20 40 60 80 100]
    t_idx = t/dt + 1;
    plot(xvec, umat(t_idx, :))
    leg = [leg "t = "+t];
end
title("Solution of the diffusion-reaction equation")
legend(leg)
xlabel("x")
ylabel("u")
hold off